export const DEACTIVATE = '__deactivate__'

export const CATEGORY_ICONS = {
  dairy_eggs: 'local_drink',
  meat: 'restaurant',
  deli: 'kebab_dining',
  fish: 'set_meal',
  water_beverages: 'water_drop',
  tea_coffee: 'coffee',
  sweets: 'cake',
  snacks: 'cookie',
  grocery: 'grain',
  sauces_spices: 'soup_kitchen',
  bread: 'bakery_dining',
  frozen: 'ac_unit',
  fruits_veg: 'nutrition',
  baby_food: 'child_care',
  ready_meals: 'bento',
  healthy: 'fitness_center',
  personal_care: 'soap',
  household: 'home',
}

export const CATEGORIES = {
  dairy_eggs: {
    ru: 'Молочные продукты и яйца',
    kz: 'Сүт өнімдері және жұмыртқа',
    subcategories: {
      milk: { ru: 'Молоко', kz: 'Сүт' },
      fermented: { ru: 'Кисломолочные', kz: 'Қышқыл сүт өнімдері' },
      cheese: { ru: 'Сыры', kz: 'Ірімшіктер' },
      butter: { ru: 'Сливочное масло', kz: 'Сары май' },
      cream: { ru: 'Сливки и сметана', kz: 'Қаймақ пен сүзбе' },
      cottage: { ru: 'Творог и сырки', kz: 'Сүзбе және ірімшіктер' },
      eggs: { ru: 'Яйца', kz: 'Жұмыртқа' },
      condensed_milk: { ru: 'Сгущённое молоко', kz: 'Қоюлатылған сүт' },
      spread: { ru: 'Спред и маргарин', kz: 'Спред пен маргарин' },
    },
  },
  meat: {
    ru: 'Мясо и птица',
    kz: 'Ет және құс',
    subcategories: {
      raw: { ru: 'Свежее мясо', kz: 'Жаңа ет' },
      poultry: { ru: 'Мясо птицы', kz: 'Құс еті' },
    },
  },
  deli: {
    ru: 'Колбасы и деликатесы',
    kz: 'Шұжықтар және деликатестер',
    subcategories: {
      sausage: { ru: 'Колбасы и сосиски', kz: 'Шұжықтар мен сосиски' },
      pate: { ru: 'Паштеты', kz: 'Паштеттер' },
      smoked: { ru: 'Копчёности', kz: 'Шыланған өнімдер' },
      deli_meat: { ru: 'Мясные деликатесы', kz: 'Ет деликатестері' },
      canned_meat: { ru: 'Мясные консервы', kz: 'Ет консервілері' },
    },
  },
  fish: {
    ru: 'Рыба и морепродукты',
    kz: 'Балық және теңіз өнімдері',
    subcategories: {
      fish: { ru: 'Рыба', kz: 'Балық' },
      seafood: { ru: 'Морепродукты', kz: 'Теңіз өнімдері' },
      canned_fish: { ru: 'Рыбные консервы', kz: 'Балық консервілері' },
    },
  },
  water_beverages: {
    ru: 'Вода и напитки',
    kz: 'Су және сусындар',
    subcategories: {
      juice: { ru: 'Соки', kz: 'Шырындар' },
      water: { ru: 'Вода', kz: 'Су' },
      soda: { ru: 'Газировка', kz: 'Газдалған сусындар' },
      energy: { ru: 'Энергетики', kz: 'Энергетикалық сусындар' },
      lemonade: { ru: 'Лимонады и квас', kz: 'Лимонадтар мен квас' },
    },
  },
  tea_coffee: {
    ru: 'Чай и кофе',
    kz: 'Шай және кофе',
    subcategories: {
      tea: { ru: 'Чай', kz: 'Шай' },
      coffee: { ru: 'Кофе', kz: 'Кофе' },
    },
  },
  sweets: {
    ru: 'Сладости',
    kz: 'Тәттілер',
    subcategories: {
      chocolate: { ru: 'Шоколад', kz: 'Шоколад' },
      candy: { ru: 'Конфеты', kz: 'Кәмпиттер' },
      cookies: { ru: 'Печенье и пряники', kz: 'Печенье мен пряниктер' },
      pastries: { ru: 'Вафли и торты', kz: 'Вафельдер мен торттар' },
      halva: { ru: 'Халва и козинаки', kz: 'Халва мен козинактер' },
      honey_jam: { ru: 'Мёд и варенье', kz: 'Бал мен варенье' },
    },
  },
  snacks: {
    ru: 'Снеки, орехи и сухофрукты',
    kz: 'Снектер, жаңғақтар және кепкен жемістер',
    subcategories: {
      chips: { ru: 'Чипсы и попкорн', kz: 'Чипстер мен попкорн' },
      crackers: { ru: 'Сухарики и крекеры', kz: 'Кепкен нан мен крекерлер' },
      nuts: { ru: 'Орехи', kz: 'Жаңғақтар' },
      dried_fruits: { ru: 'Сухофрукты', kz: 'Кепкен жемістер' },
      seeds: { ru: 'Семечки', kz: 'Тұқымдар' },
      fish_snacks: { ru: 'Рыбные снеки', kz: 'Балық снектері' },
    },
  },
  grocery: {
    ru: 'Бакалея',
    kz: 'Бакалея',
    subcategories: {
      cereals: { ru: 'Крупы', kz: 'Жарма' },
      pasta: { ru: 'Макаронные изделия', kz: 'Макарон өнімдері' },
      rice: { ru: 'Рис', kz: 'Күріш' },
      flour: { ru: 'Мука', kz: 'Ұн' },
      sugar: { ru: 'Сахар', kz: 'Қант' },
      breakfast: { ru: 'Завтраки и хлопья', kz: 'Таңғы ас пен жарма' },
      cooking_oil: { ru: 'Растительное масло', kz: 'Өсімдік майы' },
      salt: { ru: 'Соль', kz: 'Тұз' },
      vinegar: { ru: 'Уксус', kz: 'Сірке суы' },
    },
  },
  sauces_spices: {
    ru: 'Соусы и приправы',
    kz: 'Соустар және дәмдеуіштер',
    subcategories: {
      sauce: { ru: 'Соусы', kz: 'Соустар' },
      mayo_ketchup: { ru: 'Майонез и кетчуп', kz: 'Майонез пен кетчуп' },
      spices: { ru: 'Специи', kz: 'Дәмдеуіштер' },
      condiments: { ru: 'Приправы и бульоны', kz: 'Қоспалар мен сорпа' },
      soy_sauce: { ru: 'Соевый соус', kz: 'Соя соусы' },
    },
  },
  bread: {
    ru: 'Хлеб и выпечка',
    kz: 'Нан өнімдері',
    subcategories: {
      bread: { ru: 'Хлеб', kz: 'Нан' },
      pastry: { ru: 'Выпечка и булочки', kz: 'Тоқаш пен булочкалар' },
      lavash: { ru: 'Лаваши и лепёшки', kz: 'Лаваштар мен нан' },
      crispbread: { ru: 'Хлебцы', kz: 'Нан кесектері' },
    },
  },
  frozen: {
    ru: 'Замороженные',
    kz: 'Мұздатылған',
    subcategories: {
      semi_finished: { ru: 'Полуфабрикаты', kz: 'Жартылай дайын өнімдер' },
      frozen_veg: { ru: 'Замороженные овощи', kz: 'Мұздатылған көкөністер' },
      ice_cream: { ru: 'Мороженое', kz: 'Мұздық' },
      frozen_fish: { ru: 'Замороженная рыба', kz: 'Мұздатылған балық' },
      frozen_meat: { ru: 'Замороженное мясо', kz: 'Мұздатылған ет' },
    },
  },
  fruits_veg: {
    ru: 'Фрукты и овощи',
    kz: 'Жемістер және көкөністер',
    subcategories: {
      fruits: { ru: 'Фрукты', kz: 'Жемістер' },
      vegetables: { ru: 'Овощи', kz: 'Көкөністер' },
      greens: { ru: 'Зелень', kz: 'Көкөніс' },
      pickles: { ru: 'Соленья', kz: 'Тұздалған көкөністер' },
      olives: { ru: 'Оливки', kz: 'Зәйтүндер' },
      canned_veg: { ru: 'Овощные консервы', kz: 'Көкөніс консервілері' },
    },
  },
  baby_food: {
    ru: 'Детское питание',
    kz: 'Балалар тағамы',
    subcategories: {
      formula: { ru: 'Смеси', kz: 'Қоспалар' },
      puree: { ru: 'Пюре', kz: 'Пюре' },
      cereal: { ru: 'Детские каши', kz: 'Балалар жармасы' },
      baby_snacks: { ru: 'Детское печенье', kz: 'Балалар печеньесі' },
    },
  },
  ready_meals: {
    ru: 'Готовые блюда',
    kz: 'Дайын тағамдар',
    subcategories: {
      soups: { ru: 'Супы', kz: 'Сорпалар' },
      instant: { ru: 'Быстрого приготовления', kz: 'Жылдам дайындалатын' },
      ready: { ru: 'Готовые блюда', kz: 'Дайын тағамдар' },
    },
  },
  healthy: {
    ru: 'Здоровое питание',
    kz: 'Пайдалы тағамдар',
    subcategories: {
      protein: { ru: 'Протеиновые продукты', kz: 'Протеин өнімдері' },
      sugar_free: { ru: 'Без сахара', kz: 'Қантсыз' },
      gluten_free: { ru: 'Без глютена', kz: 'Глютенсіз' },
      vitamins: { ru: 'Витамины', kz: 'Дәрумендер' },
      supplements: { ru: 'БАДы', kz: 'БАД' },
      diet: { ru: 'Диетические продукты', kz: 'Диеталық өнімдер' },
    },
  },
  personal_care: {
    ru: 'Гигиена и уход',
    kz: 'Гигиена және күтім',
    subcategories: {
      shampoo: { ru: 'Шампуни', kz: 'Шампундар' },
      soap: { ru: 'Мыло', kz: 'Сабын' },
      cream: { ru: 'Кремы', kz: 'Кремдер' },
      dental: { ru: 'Зубные пасты', kz: 'Тіс пасталары' },
      hygiene: { ru: 'Средства гигиены', kz: 'Гигиена құралдары' },
    },
  },
  household: {
    ru: 'Для дома',
    kz: 'Үйге арналған',
    subcategories: {
      cleaning: { ru: 'Моющие средства', kz: 'Жуғыш құралдар' },
      paper: { ru: 'Бумага и салфетки', kz: 'Қағаз мен сүлгілер' },
      laundry: { ru: 'Для стирки', kz: 'Жууға арналған' },
      pest_control: { ru: 'От насекомых', kz: 'Жәндіктерден' },
      pet_food: { ru: 'Корм для животных', kz: 'Жануарлар жемі' },
    },
  },
}

const RAW_CATEGORY_MAP = {
  'Молочные продукты и сыры, яйцо / Сыры': { category: 'dairy_eggs', subcategory: 'cheese' },
  'Мука, соль, сахар, специи и приправы / Специи, приправы / Приправы и бульоны (для приготовления блюд)':
    { category: 'sauces_spices', subcategory: 'condiments' },
  'Макароны, крупы / Крупы': { category: 'grocery', subcategory: 'cereals' },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Вафли, пряники, печенье': {
    category: 'sweets',
    subcategory: 'cookies',
  },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Шоколад, шоколадные изделия, жевательные конфеты':
    { category: 'sweets', subcategory: 'chocolate' },
  'Напитки / Напитки, лимонады': { category: 'water_beverages', subcategory: 'lemonade' },
  'Напитки / Соки, нектары / Соки в пакетах': { category: 'water_beverages', subcategory: 'juice' },
  'Макароны, крупы / Макароны, pasta, фунчоза': { category: 'grocery', subcategory: 'pasta' },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Конфеты': {
    category: 'sweets',
    subcategory: 'candy',
  },
  'Масла растительные, соусы, майонез, уксусы / Соусы кулинарные': {
    category: 'sauces_spices',
    subcategory: 'sauce',
  },
  'Продукты быстрого приготовления, каши, мюсли / Пюре, супы, лапша': {
    category: 'ready_meals',
    subcategory: 'instant',
  },
  'Чай, кофе, кондитерские изделия / Кофе / Кофе растворимый': {
    category: 'tea_coffee',
    subcategory: 'coffee',
  },
  'Чай, кофе, кондитерские изделия / Чай / Чай черный': {
    category: 'tea_coffee',
    subcategory: 'tea',
  },
  'Снеки (чипсы, попкорн, семечки и другое) / Чипсы': { category: 'snacks', subcategory: 'chips' },
  'Консервированные продукты / Овощные закуски, огурцы и помидоры': {
    category: 'fruits_veg',
    subcategory: 'pickles',
  },
  'Масла растительные, соусы, майонез, уксусы / Кетчупы': {
    category: 'sauces_spices',
    subcategory: 'mayo_ketchup',
  },
  'Масла растительные, соусы, майонез, уксусы / Майонезы, соус майонезный': {
    category: 'sauces_spices',
    subcategory: 'mayo_ketchup',
  },
  'Консервированные продукты / Рыбные консервы': { category: 'fish', subcategory: 'canned_fish' },
  'Молочные продукты и сыры, яйцо / Творог, сырки / Десерты творожные, творожки': {
    category: 'dairy_eggs',
    subcategory: 'cottage',
  },
  'Черный чай': { category: 'tea_coffee', subcategory: 'tea' },
  'Молочные продукты и сыры, яйцо / Молоко / Молоко стерилизованное': {
    category: 'dairy_eggs',
    subcategory: 'milk',
  },
  'Молочные продукты и сыры, яйцо / Масло сливочное, маргарин, спред': {
    category: 'dairy_eggs',
    subcategory: 'butter',
  },
  'Продукты быстрого приготовления, каши, мюсли / Завтраки (хлопья)': {
    category: 'grocery',
    subcategory: 'breakfast',
  },
  'Лаваши и лепешки': { category: 'bread', subcategory: 'lavash' },
  'Снеки (чипсы, попкорн, семечки и другое) / Сухарики, гренки': {
    category: 'snacks',
    subcategory: 'crackers',
  },
  'Снеки (чипсы, попкорн, семечки и другое) / Семечки, орешки соленые': {
    category: 'snacks',
    subcategory: 'seeds',
  },
  'Кефир, ряженка': { category: 'dairy_eggs', subcategory: 'fermented' },
  'Печенье, крекеры': { category: 'sweets', subcategory: 'cookies' },
  'Чай, кофе, кондитерские изделия / Чай / Чай с добавками': {
    category: 'tea_coffee',
    subcategory: 'tea',
  },
  'Консервированные продукты / Фруктовые и ягодные консервы': {
    category: 'fruits_veg',
    subcategory: 'canned_veg',
  },
  'EURO маркет / Напитки': { category: 'water_beverages', subcategory: null },
  'Комбуча и квас': { category: 'water_beverages', subcategory: 'lemonade' },
  'Мука, соль, сахар, специи и приправы / Специи, приправы / Специи (для выпечки)': {
    category: 'sauces_spices',
    subcategory: 'spices',
  },
  'Молочные продукты и сыры, яйцо / Йогурты / Йогурты питьевые': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  'Напитки / Энергетики': { category: 'water_beverages', subcategory: 'energy' },
  'Конфеты в коробках': { category: 'sweets', subcategory: 'candy' },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Жевательная резинка': {
    category: 'sweets',
    subcategory: 'candy',
  },
  'Растворимый кофе': { category: 'tea_coffee', subcategory: 'coffee' },
  'Мясо, мясо птицы, рыба / Рыба и морепродукты / Рыба и морепродукты переработанные': {
    category: 'fish',
    subcategory: 'seafood',
  },
  'Мука, соль, сахар, специи и приправы / Мука, соль, сахар': {
    category: 'grocery',
    subcategory: 'flour',
  },
  'Подсолнечное масло': { category: 'grocery', subcategory: 'cooking_oil' },
  'Масла растительные, соусы, майонез, уксусы / Масло подсолнечное, оливковое и другие / Масло оливковое и другие':
    { category: 'grocery', subcategory: 'cooking_oil' },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Халва, козинаки, рахат-лукум, щербет':
    { category: 'sweets', subcategory: 'halva' },
  'Напитки / Квас, холодный чай, кофе': { category: 'water_beverages', subcategory: 'lemonade' },
  'Напитки / Соки, нектары / Соки в стекле': { category: 'water_beverages', subcategory: 'juice' },
  'Консервированные продукты / Мясные консервы': { category: 'deli', subcategory: 'canned_meat' },
  'Продукты быстрого приготовления, каши, мюсли / Каши, мюсли и батончики': {
    category: 'grocery',
    subcategory: 'breakfast',
  },
  'Творожные сырки': { category: 'dairy_eggs', subcategory: 'cottage' },
  'Чай, кофе, кондитерские изделия / Кофе / Кофе растворимый (разовые пакеты)': {
    category: 'tea_coffee',
    subcategory: 'coffee',
  },
  'Перец, специи': { category: 'sauces_spices', subcategory: 'spices' },
  'Консервированные продукты / Оливки, маслины, грибы, томатная паста / Томатная паста': {
    category: 'sauces_spices',
    subcategory: 'condiments',
  },
  'ПП-соусы, масла и специи': { category: 'sauces_spices', subcategory: 'condiments' },
  'Плиточный шоколад': { category: 'sweets', subcategory: 'chocolate' },
  'Консервированные продукты / Оливки, маслины, грибы, томатная паста / Оливки и маслины': {
    category: 'fruits_veg',
    subcategory: 'olives',
  },
  'Консервированные продукты / Горошек, кукуруза, фасоль': {
    category: 'fruits_veg',
    subcategory: 'canned_veg',
  },
  'Молочные продукты и сыры, яйцо / Йогурты / Йогурты в стаканчиках': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Варенье, джем, мед, сиропы':
    { category: 'sweets', subcategory: 'honey_jam' },
  'Снеки (чипсы, попкорн, семечки и другое) / Кукурузные палочки и попкорн': {
    category: 'snacks',
    subcategory: 'chips',
  },
  'Хлеб, булочки, лепешки / Хлебцы, слайсы': { category: 'bread', subcategory: 'crispbread' },
  'Мясо, мясо птицы, рыба / Мясо птицы / Мясо птицы замороженное': {
    category: 'meat',
    subcategory: 'poultry',
  },
  'Напитки / Растительные напитки': { category: 'water_beverages', subcategory: 'lemonade' },
  'Оливковое масло': { category: 'grocery', subcategory: 'cooking_oil' },
  'Универсальные приправы, бульоны': { category: 'sauces_spices', subcategory: 'condiments' },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Мармелад': {
    category: 'sweets',
    subcategory: 'candy',
  },
  'Густые йогурты': { category: 'dairy_eggs', subcategory: 'fermented' },
  'Молоко альтернативное': { category: 'dairy_eggs', subcategory: 'milk' },
  'Соки, нектары': { category: 'water_beverages', subcategory: 'juice' },
  'Напитки / Вода / Вода минеральная': { category: 'water_beverages', subcategory: 'water' },
  'Водоросли нори': { category: 'fish', subcategory: 'seafood' },
  'Молочные продукты и сыры, яйцо / Концентрированное и сгущенное молоко / Сгущенное молоко': {
    category: 'dairy_eggs',
    subcategory: 'condensed_milk',
  },
  Сосиски: { category: 'deli', subcategory: 'sausage' },
  'Влажные корма для кошек': { category: 'household', subcategory: 'pet_food' },
  'Молочные продукты и сыры, яйцо / Сметана': { category: 'dairy_eggs', subcategory: 'cream' },
  'EURO маркет / Продукты быстрого приготовления, каши, мюсли': {
    category: 'ready_meals',
    subcategory: 'instant',
  },
  'Молочные продукты и сыры, яйцо / Сливки / Сливки': {
    category: 'dairy_eggs',
    subcategory: 'cream',
  },
  'Кофе в зёрнах': { category: 'tea_coffee', subcategory: 'coffee' },
  'Красные соусы': { category: 'sauces_spices', subcategory: 'sauce' },
  'Молочные продукты и сыры, яйцо / Творог, сырки / Творожные сырки': {
    category: 'dairy_eggs',
    subcategory: 'cottage',
  },
  'Овощные консервы': { category: 'fruits_veg', subcategory: 'canned_veg' },
  'Молочные продукты и сыры, яйцо / Кисломолочные продукты / Кефир': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  'Соусы и уксусы': { category: 'sauces_spices', subcategory: 'sauce' },
  Плавленый: { category: 'dairy_eggs', subcategory: 'cheese' },
  'Сардельки, шпикачки': { category: 'deli', subcategory: 'sausage' },
  'Мясо, мясо птицы, рыба / Рыба и морепродукты / Рыба и морепродукты замороженные': {
    category: 'fish',
    subcategory: 'fish',
  },
  Попкорн: { category: 'snacks', subcategory: 'chips' },
  Пельмени: { category: 'frozen', subcategory: 'semi_finished' },
  Яйца: { category: 'dairy_eggs', subcategory: 'eggs' },
  'Твёрдый и полутвердый': { category: 'dairy_eggs', subcategory: 'cheese' },
  'EURO маркет / Кондитерские изделия': { category: 'sweets', subcategory: null },
  'Напитки / Вода / Вода (газированная и негазированная)': {
    category: 'water_beverages',
    subcategory: 'water',
  },
  'Рыбные консервы': { category: 'fish', subcategory: 'canned_fish' },
  'Макаронные изделия': { category: 'grocery', subcategory: 'pasta' },
  'Комбуча, квас': { category: 'water_beverages', subcategory: 'lemonade' },
  'Масла растительные, соусы, майонез, уксусы / Масло подсолнечное, оливковое и другие / Масло подсолнечное':
    { category: 'grocery', subcategory: 'cooking_oil' },
  'EURO маркет / Консервированные продукты': { category: 'fruits_veg', subcategory: 'canned_veg' },
  'Мюсли, гранола': { category: 'grocery', subcategory: 'breakfast' },
  'Газировка и лимонад': { category: 'water_beverages', subcategory: 'soda' },
  'Чай, кофе, кондитерские изделия / Кондитерские изделия и сладости / Торты, пирожные, десерты, пироги':
    { category: 'sweets', subcategory: 'pastries' },
  'Молочные продукты и сыры, яйцо / Кисломолочные продукты / Курт, жент': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  'Зефир, мармелад, пастила': { category: 'sweets', subcategory: 'candy' },
  'Молочные продукты и сыры, яйцо / Кисломолочные продукты / Ряженка, катык': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  Негазированная: { category: 'water_beverages', subcategory: 'water' },
  'Сырокопчёные и сыровяленые': { category: 'deli', subcategory: 'smoked' },
  Майонез: { category: 'sauces_spices', subcategory: 'mayo_ketchup' },
  'Уксус, эссенция': { category: 'grocery', subcategory: 'vinegar' },
  'Горошек, кукуруза, бобовые': { category: 'fruits_veg', subcategory: 'canned_veg' },
  'Творожный и сливочный': { category: 'dairy_eggs', subcategory: 'cheese' },
  Каши: { category: 'grocery', subcategory: 'breakfast' },
  'Зерновые хлопья': { category: 'grocery', subcategory: 'breakfast' },
  'Пшеничная мука': { category: 'grocery', subcategory: 'flour' },
  'Восточные сладости': { category: 'sweets', subcategory: 'halva' },
  'Огурцы, помидоры, ассорти': { category: 'fruits_veg', subcategory: 'pickles' },
  'Специи органические': { category: 'sauces_spices', subcategory: 'spices' },
  'Котлеты, тефтели': { category: 'frozen', subcategory: 'semi_finished' },
  'Растворимый кофе и какао': { category: 'tea_coffee', subcategory: 'coffee' },
  'На палочке': { category: 'frozen', subcategory: 'ice_cream' },
  'Чай, кофе, кондитерские изделия / Какао': { category: 'tea_coffee', subcategory: 'coffee' },
  'Травяные и фруктовые чаи': { category: 'tea_coffee', subcategory: 'tea' },
  Масла: { category: 'grocery', subcategory: 'cooking_oil' },
  'Сухие завтраки, гранолы': { category: 'grocery', subcategory: 'breakfast' },
  Гречка: { category: 'grocery', subcategory: 'cereals' },
  'Молочные продукты и сыры, яйцо / Молоко / Молоко короткого хранения': {
    category: 'dairy_eggs',
    subcategory: 'milk',
  },
  'Сосиски, сардельки Халал': { category: 'deli', subcategory: 'sausage' },
  'Напитки / Растворимый кисель': { category: 'water_beverages', subcategory: 'lemonade' },
  'Мясо, мясо птицы, рыба / Мясо, мясо в маринадах / Мясо и фарши охлажденные': {
    category: 'meat',
    subcategory: 'raw',
  },
  'Сок, вода': { category: 'water_beverages', subcategory: null },
  'Лакомства для кошек': { category: 'household', subcategory: 'pet_food' },
  Минеральная: { category: 'water_beverages', subcategory: 'water' },
  'Детская бакалея': { category: 'baby_food', subcategory: 'cereal' },
  'Снеки (чипсы, попкорн, семечки и другое) / Снеки из морепродуктов, сыр чечил': {
    category: 'snacks',
    subcategory: 'fish_snacks',
  },
  'Фета и рассольные сыры': { category: 'dairy_eggs', subcategory: 'cheese' },
  'Энергетические напитки': { category: 'water_beverages', subcategory: 'energy' },
  'Чай, кофе, кондитерские изделия / Кофе / Кофе для варки': {
    category: 'tea_coffee',
    subcategory: 'coffee',
  },
  'Молочные продукты и сыры, яйцо / Яйцо': { category: 'dairy_eggs', subcategory: 'eggs' },
  'Мясо, мясо птицы, рыба / Мясо птицы / Мясо птицы охлажденное': {
    category: 'meat',
    subcategory: 'poultry',
  },
  'Масла растительные, соусы, майонез, уксусы / Уксусы, маринады': {
    category: 'grocery',
    subcategory: 'vinegar',
  },
  'Пицца замороженная': { category: 'frozen', subcategory: 'semi_finished' },
  'Хлеб, булочки, лепешки / Лаваши, лепешки': { category: 'bread', subcategory: 'lavash' },
  Варёные: { category: 'deli', subcategory: 'sausage' },
  'Для сэндвичей и бутербродов': { category: 'bread', subcategory: 'pastry' },
  Нарезки: { category: 'deli', subcategory: 'deli_meat' },
  Вафли: { category: 'sweets', subcategory: 'pastries' },
  'Горчица, хрен': { category: 'sauces_spices', subcategory: 'condiments' },
  'Здоровое питание / Товары с сахарозаменителем и другое': {
    category: 'healthy',
    subcategory: 'sugar_free',
  },
  Соки: { category: 'water_beverages', subcategory: 'juice' },
  Пряники: { category: 'sweets', subcategory: 'cookies' },
  'Зубные пасты': { category: 'personal_care', subcategory: 'dental' },
  'Колбаса, сосиcки, сало, деликатесы из мяса / Сосиски, сардельки и шпикачки': {
    category: 'deli',
    subcategory: 'sausage',
  },
  'Национальные продукты': { category: 'dairy_eggs', subcategory: 'fermented' },
  'Томатная паста, протёртые томаты': { category: 'sauces_spices', subcategory: 'condiments' },
  'Полуфабрикаты / Изделия из птицы и рыбы': { category: 'frozen', subcategory: 'semi_finished' },
  Ветчина: { category: 'deli', subcategory: 'deli_meat' },
  'Хлеб и хлебцы без глютена': { category: 'healthy', subcategory: 'gluten_free' },
  'Другие соусы': { category: 'sauces_spices', subcategory: 'sauce' },
  'Сладости и батончики без сахара': { category: 'healthy', subcategory: 'sugar_free' },
  'Молотый кофе': { category: 'tea_coffee', subcategory: 'coffee' },
  'Соль, сахар и заменители': { category: 'grocery', subcategory: 'sugar' },
  'Соки, вода': { category: 'water_beverages', subcategory: null },
  Джемы: { category: 'sweets', subcategory: 'honey_jam' },
  'Перекусы и завтраки': { category: 'grocery', subcategory: 'breakfast' },
  'Зелёный чай': { category: 'tea_coffee', subcategory: 'tea' },
  Сметана: { category: 'dairy_eggs', subcategory: 'cream' },
  'Тесто замороженное': { category: 'frozen', subcategory: 'semi_finished' },
  'Шоколад без сахара': { category: 'healthy', subcategory: 'sugar_free' },
  'EURO маркет / Молочные продукты и сыры': { category: 'dairy_eggs', subcategory: null },
  'Рыбные полуфабрикаты': { category: 'fish', subcategory: 'fish' },
  'Товары для детей / Детское питание / Напитки': { category: 'baby_food', subcategory: null },
  Сахар: { category: 'grocery', subcategory: 'sugar' },
  'Конфеты весовые': { category: 'sweets', subcategory: 'candy' },
  'Для посудомоечных машин': { category: 'household', subcategory: 'cleaning' },
  'Икорные закуски и паста': { category: 'fish', subcategory: 'seafood' },
  'Кисломолочный продукт ПП': { category: 'dairy_eggs', subcategory: 'fermented' },
  'Мыло твёрдое и жидкое': { category: 'personal_care', subcategory: 'soap' },
  'Молочные продукты и сыры, яйцо / Кисломолочные продукты / Снежок, Био-С, сладкий кефир': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  'Шоколадные батончики': { category: 'sweets', subcategory: 'chocolate' },
  'Хлеб, булочки, лепешки / Сушки, баранки, хлебные палочки': {
    category: 'snacks',
    subcategory: 'crackers',
  },
  'Полуфабрикаты / Котлеты, тефтели, фарш': { category: 'frozen', subcategory: 'semi_finished' },
  'Батончики, печенье и снеки без глютена': { category: 'healthy', subcategory: 'gluten_free' },
  'Мука без глютена': { category: 'healthy', subcategory: 'gluten_free' },
  Орехи: { category: 'snacks', subcategory: 'nuts' },
  'Молочные продукты и сыры, яйцо / Концентрированное и сгущенное молоко / Молочные коктейли': {
    category: 'dairy_eggs',
    subcategory: 'milk',
  },
  'Моноовощи замороженные': { category: 'frozen', subcategory: 'frozen_veg' },
  Бобовые: { category: 'grocery', subcategory: 'cereals' },
  'Хлебцы и здоровый хлеб': { category: 'bread', subcategory: 'crispbread' },
  'Пюре мясные и рыбные': { category: 'baby_food', subcategory: 'puree' },
  'Спагетти, лингвини': { category: 'grocery', subcategory: 'pasta' },
  'Питьевые йогурты': { category: 'dairy_eggs', subcategory: 'fermented' },
  'Молочные продукты и сыры, яйцо / Кисломолочные продукты / Тан': {
    category: 'dairy_eggs',
    subcategory: 'fermented',
  },
  'ПП-обеды': { category: 'healthy', subcategory: 'diet' },
  Кетчуп: { category: 'sauces_spices', subcategory: 'mayo_ketchup' },
  'Смеси для выпечки': { category: 'grocery', subcategory: 'flour' },
  'Блинчики, круассаны, сырники': { category: 'frozen', subcategory: 'semi_finished' },
  Вареники: { category: 'frozen', subcategory: 'semi_finished' },
  'Творог, творожная масса': { category: 'dairy_eggs', subcategory: 'cottage' },
  'Батончики, брикеты': { category: 'frozen', subcategory: 'ice_cream' },
  'Сухие корма для собак': { category: 'household', subcategory: 'pet_food' },
  Крупа: { category: 'grocery', subcategory: 'cereals' },
  'Чечил и копченые сыры': { category: 'dairy_eggs', subcategory: 'cheese' },
  'С плесенью': { category: 'dairy_eggs', subcategory: 'cheese' },
  'Моцарелла и мягкие сыры': { category: 'dairy_eggs', subcategory: 'cheese' },
  'Колбаса, сосиcки, сало, деликатесы из мяса / Колбасы / Полукопченая колбаса': {
    category: 'deli',
    subcategory: 'sausage',
  },
  'Консервированные продукты / Паштеты мясные и каши консервированные / Паштеты мясные': {
    category: 'deli',
    subcategory: 'pate',
  },
  'Закуски к пиву': { category: 'snacks', subcategory: 'fish_snacks' },
  'Батончики и снеки': { category: 'snacks', subcategory: 'chips' },
  'Каши и завтраки': { category: 'grocery', subcategory: 'breakfast' },
  'Копченые Халал': { category: 'deli', subcategory: 'smoked' },
  'Дрессинги, заправки': { category: 'sauces_spices', subcategory: 'condiments' },
  Какао: { category: 'tea_coffee', subcategory: 'coffee' },
  'В стаканчике': { category: 'frozen', subcategory: 'ice_cream' },
  'Варёные Халал': { category: 'deli', subcategory: 'sausage' },
  'Копченые колбасы': { category: 'deli', subcategory: 'smoked' },
  'Сухие корма для кошек': { category: 'household', subcategory: 'pet_food' },
  'Напитки / Кисель, компот, морс': { category: 'water_beverages', subcategory: 'lemonade' },
  'Смеси и каши': { category: 'baby_food', subcategory: 'cereal' },
  'Сливочное масло': { category: 'dairy_eggs', subcategory: 'butter' },
  Рис: { category: 'grocery', subcategory: 'rice' },
  'Макароны фигурные': { category: 'grocery', subcategory: 'pasta' },
  Молоко: { category: 'dairy_eggs', subcategory: 'milk' },
  Сухарики: { category: 'snacks', subcategory: 'crackers' },
  Картофельные: { category: 'snacks', subcategory: 'chips' },
  Наггетсы: { category: 'frozen', subcategory: 'semi_finished' },
  'Белый, черный': { category: 'bread', subcategory: 'bread' },
  'Ведерки и большие упаковки': { category: 'frozen', subcategory: 'ice_cream' },
  'Жевательная резинка, мятные леденцы': { category: 'sweets', subcategory: 'candy' },
  'Кондитерские добавки': { category: 'grocery', subcategory: 'flour' },
  'Консервированные продукты / Оливки, маслины, грибы, томатная паста / Грибы консервированные': {
    category: 'fruits_veg',
    subcategory: 'canned_veg',
  },
  'Грибные консервы': { category: 'fruits_veg', subcategory: 'canned_veg' },
  Консервация: { category: 'fruits_veg', subcategory: 'canned_veg' },
  'Кукуруза, горох, спаржа': { category: 'fruits_veg', subcategory: 'canned_veg' },
  Тоники: { category: 'water_beverages', subcategory: 'soda' },
  Драже: { category: 'sweets', subcategory: 'candy' },
  'Макароны без глютена': { category: 'grocery', subcategory: 'pasta' },
  'Из птицы': { category: 'meat', subcategory: 'poultry' },
  'Мясо копчёное, вяленое': { category: 'deli', subcategory: 'smoked' },
  'Полуфабрикаты / Почти готово!': { category: 'frozen', subcategory: 'semi_finished' },
  breakfasts: { category: 'grocery', subcategory: 'breakfast' },
  Полукопчёные: { category: 'deli', subcategory: 'smoked' },
  Креветки: { category: 'fish', subcategory: 'seafood' },
  Панировка: { category: 'grocery', subcategory: 'flour' },
  'Влажные корма для собак': { category: 'household', subcategory: 'pet_food' },
  'Мыло кусковое': { category: 'personal_care', subcategory: 'soap' },
  'Жайма, сочни, лапша': { category: 'grocery', subcategory: 'pasta' },
  'Средства для полов': { category: 'household', subcategory: 'cleaning' },
  'Яблоки, груши': { category: 'fruits_veg', subcategory: 'fruits' },
  'Сиропы и топпинги': { category: 'sweets', subcategory: 'honey_jam' },
  'Подгузники, пеленки': { category: 'household', subcategory: 'hygiene' },
  'Хлеб, булочки, лепешки / Сухари, сушеный хлеб, гренки': {
    category: 'snacks',
    subcategory: 'crackers',
  },
  'Лосьоны, тоники, тонеры': { category: 'personal_care', subcategory: 'cream' },
  'Гели для душа': { category: 'personal_care', subcategory: 'hygiene' },
  'Заменители молока, смеси': { category: 'baby_food', subcategory: 'formula' },
  'Мясной фарш': { category: 'meat', subcategory: 'raw' },
  'Средства для кухни, ванной': { category: 'household', subcategory: 'cleaning' },
  'ПП-десерты': { category: 'healthy', subcategory: 'diet' },
  'Азиатские соусы': { category: 'sauces_spices', subcategory: 'soy_sauce' },
  'Чипсы из морской капусты': { category: 'snacks', subcategory: 'fish_snacks' },
  'Рыба солёная': { category: 'fish', subcategory: 'canned_fish' },
  Выпечка: { category: 'bread', subcategory: 'pastry' },
  'Варёно-копчёные': { category: 'deli', subcategory: 'smoked' },
  'Веган полуфабрикаты': { category: 'frozen', subcategory: 'semi_finished' },
  'Консервированные продукты / Паштеты мясные и каши консервированные / Каши мясные консервированные':
    { category: 'deli', subcategory: 'canned_meat' },
  'Молочные продукты и сыры, яйцо / Сливки / Молочные десерты': {
    category: 'dairy_eggs',
    subcategory: 'cream',
  },
  'Для ручного мытья посуды': { category: 'household', subcategory: 'cleaning' },
  'EURO маркет / Мясо, мясо птицы, рыба': { category: 'fish', subcategory: null },
  beverages: { category: 'water_beverages', subcategory: null },
  'beverages-and-beverages-preparations': { category: 'water_beverages', subcategory: null },
  desserts: { category: 'sweets', subcategory: 'candy' },
  dairies: { category: 'dairy_eggs', subcategory: null },
}

const RAW_SUBCATEGORY_MAP = {
  Сыры: { subcategory: 'cheese' },
  'Приправы и бульоны (для приготовления блюд)': { subcategory: 'condiments' },
  Крупы: { subcategory: 'cereals' },
  'Вафли, пряники, печенье': { subcategory: 'cookies' },
  chocolate: { subcategory: 'chocolate' },
  'Шоколад, шоколадные изделия, жевательные конфеты': { subcategory: 'chocolate' },
  'Напитки, лимонады': { subcategory: 'lemonade' },
  'Соки в пакетах': { subcategory: 'juice' },
  'Макароны, pasta, фунчоза': { subcategory: 'pasta' },
  Конфеты: { subcategory: 'candy' },
  'Соусы кулинарные': { subcategory: 'sauce' },
  'Пюре, супы, лапша': { subcategory: 'instant' },
  'Кофе растворимый': { subcategory: 'coffee' },
  'Чай черный': { subcategory: 'tea' },
  Чипсы: { subcategory: 'chips' },
  'Овощные закуски, огурцы и помидоры': { subcategory: 'pickles' },
  Кетчупы: { subcategory: 'mayo_ketchup' },
  'Майонезы, соус майонезный': { subcategory: 'mayo_ketchup' },
  'Рыбные консервы': { subcategory: 'canned_fish' },
  'Десерты творожные, творожки': { subcategory: 'cottage' },
  'Молоко стерилизованное': { subcategory: 'milk' },
  'Масло сливочное, маргарин, спред': { subcategory: 'butter' },
  'Завтраки (хлопья)': { subcategory: 'breakfast' },
  Напитки: { subcategory: null },
  'Сухарики, гренки': { subcategory: 'crackers' },
  'Семечки, орешки соленые': { subcategory: 'seeds' },
  'Чай с добавками': { subcategory: 'tea' },
  'Фруктовые и ягодные консервы': { subcategory: 'canned_veg' },
  'Специи (для выпечки)': { subcategory: 'spices' },
  'Йогурты питьевые': { subcategory: 'fermented' },
  Энергетики: { subcategory: 'energy' },
  'Жевательная резинка': { subcategory: 'candy' },
  'Рыба и морепродукты переработанные': { subcategory: 'seafood' },
  'Мука, соль, сахар': { subcategory: 'flour' },
  'Масло оливковое и другие': { subcategory: 'cooking_oil' },
  'Халва, козинаки, рахат-лукум, щербет': { subcategory: 'halva' },
  'Квас, холодный чай, кофе': { subcategory: 'lemonade' },
  'Соки в стекле': { subcategory: 'juice' },
  'Мясные консервы': { subcategory: 'canned_meat' },
  'Каши, мюсли и батончики': { subcategory: 'breakfast' },
  'Кофе растворимый (разовые пакеты)': { subcategory: 'coffee' },
  'Томатная паста': { subcategory: 'condiments' },
  'Оливки и маслины': { subcategory: 'olives' },
  'Горошек, кукуруза, фасоль': { subcategory: 'canned_veg' },
  'Йогурты в стаканчиках': { subcategory: 'fermented' },
  'Варенье, джем, мед, сиропы': { subcategory: 'honey_jam' },
  'Кукурузные палочки и попкорн': { subcategory: 'chips' },
  'Хлебцы, слайсы': { subcategory: 'crispbread' },
  'Мясо птицы замороженное': { subcategory: 'poultry' },
  'Растительные напитки': { subcategory: 'lemonade' },
  Мармелад: { subcategory: 'candy' },
  'Вода минеральная': { subcategory: 'water' },
  'Сгущенное молоко': { subcategory: 'condensed_milk' },
  Сметана: { subcategory: 'cream' },
  'Продукты быстрого приготовления, каши, мюсли': { subcategory: 'instant' },
  Сливки: { subcategory: 'cream' },
  'Творожные сырки': { subcategory: 'cottage' },
  Кефир: { subcategory: 'fermented' },
  'Рыба и морепродукты замороженные': { subcategory: 'fish' },
  'Кондитерские изделия': { subcategory: null },
  'Вода (газированная и негазированная)': { subcategory: 'water' },
  'Масло подсолнечное': { subcategory: 'cooking_oil' },
  'Консервированные продукты': { subcategory: 'canned_veg' },
  'Торты, пирожные, десерты, пироги': { subcategory: 'pastries' },
  'Курт, жент': { subcategory: 'fermented' },
  'Ряженка, катык': { subcategory: 'fermented' },
  Какао: { subcategory: 'coffee' },
  'Молоко короткого хранения': { subcategory: 'milk' },
  'Растворимый кисель': { subcategory: 'lemonade' },
  'Мясо и фарши охлажденные': { subcategory: 'raw' },
  'Снеки из морепродуктов, сыр чечил': { subcategory: 'fish_snacks' },
  'Кофе для варки': { subcategory: 'coffee' },
  Яйцо: { subcategory: 'eggs' },
  'Мясо птицы охлажденное': { subcategory: 'poultry' },
  'Уксусы, маринады': { subcategory: 'vinegar' },
  'Лаваши, лепешки': { subcategory: 'lavash' },
  'Товары с сахарозаменителем и другое': { subcategory: 'sugar_free' },
  'Сосиски, сардельки и шпикачки': { subcategory: 'sausage' },
  'Изделия из птицы и рыбы': { subcategory: 'semi_finished' },
  beer: { subcategory: 'lemonade' },
  juice: { subcategory: 'juice' },
  'Молочные продукты и сыры': { subcategory: null },
  baby_food: { subcategory: 'cereal' },
  'Снежок, Био-С, сладкий кефир': { subcategory: 'fermented' },
  'Сушки, баранки, хлебные палочки': { subcategory: 'crackers' },
  'Котлеты, тефтели, фарш': { subcategory: 'semi_finished' },
  'Молочные коктейли': { subcategory: 'milk' },
  Тан: { subcategory: 'fermented' },
  'Полукопченая колбаса': { subcategory: 'sausage' },
  'Паштеты мясные': { subcategory: 'pate' },
  'Кисель, компот, морс': { subcategory: 'lemonade' },
}

const NAME_KEYWORDS = [
  { pattern: 'шоколадная паста', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'шоколадное печенье', cat: 'sweets', sub: 'cookies' },
  { pattern: 'шоколадный батончик', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'шоколадные конфеты', cat: 'sweets', sub: 'candy' },
  { pattern: 'шоколадная плитка', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'молочный шоколад', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'горький шоколад', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'белый шоколад', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'темный шоколад', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'тёмный шоколад', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'шоколад', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'chocolate', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'печенье', cat: 'sweets', sub: 'cookies' },
  { pattern: 'крекер', cat: 'sweets', sub: 'cookies' },
  { pattern: 'пряник', cat: 'sweets', sub: 'cookies' },
  { pattern: 'вафл', cat: 'sweets', sub: 'pastries' },
  { pattern: 'конфет', cat: 'sweets', sub: 'candy' },
  { pattern: 'карамел', cat: 'sweets', sub: 'candy' },
  { pattern: 'мармелад', cat: 'sweets', sub: 'candy' },
  { pattern: 'зефир', cat: 'sweets', sub: 'candy' },
  { pattern: 'халв', cat: 'sweets', sub: 'halva' },
  { pattern: 'козинак', cat: 'sweets', sub: 'halva' },
  { pattern: 'рахат-лукум', cat: 'sweets', sub: 'halva' },
  { pattern: 'щербет', cat: 'sweets', sub: 'halva' },
  { pattern: 'чак-чак', cat: 'sweets', sub: 'halva' },
  { pattern: 'мёд', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'варень', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'джем', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'молок', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'кефир', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'ряженк', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'йогурт', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'снежок', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'кумыс', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'тан ', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'айран', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'курт', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'сыр ', cat: 'dairy_eggs', sub: 'cheese' },
  { pattern: 'сырок', cat: 'dairy_eggs', sub: 'cottage' },
  { pattern: 'творог', cat: 'dairy_eggs', sub: 'cottage' },
  { pattern: 'сметан', cat: 'dairy_eggs', sub: 'cream' },
  { pattern: 'сливк', cat: 'dairy_eggs', sub: 'cream' },
  { pattern: 'сливочное масло', cat: 'dairy_eggs', sub: 'butter' },
  { pattern: 'масло сливочное', cat: 'dairy_eggs', sub: 'butter' },
  { pattern: 'сгущенк', cat: 'dairy_eggs', sub: 'condensed_milk' },
  { pattern: 'сгущёнк', cat: 'dairy_eggs', sub: 'condensed_milk' },
  { pattern: 'яйц', cat: 'dairy_eggs', sub: 'eggs' },
  { pattern: 'спред', cat: 'dairy_eggs', sub: 'spread' },
  { pattern: 'маргарин', cat: 'dairy_eggs', sub: 'spread' },
  { pattern: 'колбас', cat: 'deli', sub: 'sausage' },
  { pattern: 'сосиск', cat: 'deli', sub: 'sausage' },
  { pattern: 'сардельк', cat: 'deli', sub: 'sausage' },
  { pattern: 'шпикачк', cat: 'deli', sub: 'sausage' },
  { pattern: 'паштет', cat: 'deli', sub: 'pate' },
  { pattern: 'ветчин', cat: 'deli', sub: 'deli_meat' },
  { pattern: 'балык', cat: 'deli', sub: 'deli_meat' },
  { pattern: 'нарезк', cat: 'deli', sub: 'deli_meat' },
  { pattern: 'салями', cat: 'deli', sub: 'smoked' },
  { pattern: 'копчён', cat: 'deli', sub: 'smoked' },
  { pattern: 'копчен', cat: 'deli', sub: 'smoked' },
  { pattern: 'тушёнк', cat: 'deli', sub: 'canned_meat' },
  { pattern: 'тушенк', cat: 'deli', sub: 'canned_meat' },
  { pattern: 'мясные консерв', cat: 'deli', sub: 'canned_meat' },
  { pattern: 'рыб', cat: 'fish', sub: 'fish' },
  { pattern: 'креветк', cat: 'fish', sub: 'seafood' },
  { pattern: 'кальмар', cat: 'fish', sub: 'seafood' },
  { pattern: 'миди', cat: 'fish', sub: 'seafood' },
  { pattern: 'крабов', cat: 'fish', sub: 'seafood' },
  { pattern: 'морепродукт', cat: 'fish', sub: 'seafood' },
  { pattern: 'икр', cat: 'fish', sub: 'seafood' },
  { pattern: 'нори', cat: 'fish', sub: 'seafood' },
  { pattern: 'тунец', cat: 'fish', sub: 'canned_fish' },
  { pattern: 'сайр', cat: 'fish', sub: 'canned_fish' },
  { pattern: 'сардин', cat: 'fish', sub: 'canned_fish' },
  { pattern: 'сок', cat: 'water_beverages', sub: 'juice' },
  { pattern: 'нектар', cat: 'water_beverages', sub: 'juice' },
  { pattern: 'вода', cat: 'water_beverages', sub: 'water' },
  { pattern: 'газировк', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'лимонад', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'квас', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'комбуч', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'энергетик', cat: 'water_beverages', sub: 'energy' },
  { pattern: 'кисель', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'компот', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'морс', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'coca-cola', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'pepsi', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'fanta', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'sprite', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'чай', cat: 'tea_coffee', sub: 'tea' },
  { pattern: 'кофе', cat: 'tea_coffee', sub: 'coffee' },
  { pattern: 'какао', cat: 'tea_coffee', sub: 'coffee' },
  { pattern: 'coffee', cat: 'tea_coffee', sub: 'coffee' },
  { pattern: 'tea ', cat: 'tea_coffee', sub: 'tea' },
  { pattern: 'чипс', cat: 'snacks', sub: 'chips' },
  { pattern: 'попкорн', cat: 'snacks', sub: 'chips' },
  { pattern: 'сухарик', cat: 'snacks', sub: 'crackers' },
  { pattern: 'гренк', cat: 'snacks', sub: 'crackers' },
  { pattern: 'орех', cat: 'snacks', sub: 'nuts' },
  { pattern: 'миндал', cat: 'snacks', sub: 'nuts' },
  { pattern: 'фундук', cat: 'snacks', sub: 'nuts' },
  { pattern: 'арахис', cat: 'snacks', sub: 'nuts' },
  { pattern: 'фисташк', cat: 'snacks', sub: 'nuts' },
  { pattern: 'кешью', cat: 'snacks', sub: 'nuts' },
  { pattern: 'сухофрукт', cat: 'snacks', sub: 'dried_fruits' },
  { pattern: 'кураг', cat: 'snacks', sub: 'dried_fruits' },
  { pattern: 'изюм', cat: 'snacks', sub: 'dried_fruits' },
  { pattern: 'чернослив', cat: 'snacks', sub: 'dried_fruits' },
  { pattern: 'семечк', cat: 'snacks', sub: 'seeds' },
  { pattern: 'подсолнечник', cat: 'snacks', sub: 'seeds' },
  { pattern: 'тыквенн', cat: 'snacks', sub: 'seeds' },
  { pattern: 'жареный', cat: 'snacks', sub: 'seeds' },
  { pattern: 'соленый', cat: 'snacks', sub: 'seeds' },
  { pattern: 'круп', cat: 'grocery', sub: 'cereals' },
  { pattern: 'гречк', cat: 'grocery', sub: 'cereals' },
  { pattern: 'овсян', cat: 'grocery', sub: 'cereals' },
  { pattern: 'пшено', cat: 'grocery', sub: 'cereals' },
  { pattern: 'перлов', cat: 'grocery', sub: 'cereals' },
  { pattern: 'манн', cat: 'grocery', sub: 'cereals' },
  { pattern: 'макарон', cat: 'grocery', sub: 'pasta' },
  { pattern: 'спагетти', cat: 'grocery', sub: 'pasta' },
  { pattern: 'паста', cat: 'grocery', sub: 'pasta' },
  { pattern: 'фунчоз', cat: 'grocery', sub: 'pasta' },
  { pattern: 'рис', cat: 'grocery', sub: 'rice' },
  { pattern: 'мука', cat: 'grocery', sub: 'flour' },
  { pattern: 'сахар', cat: 'grocery', sub: 'sugar' },
  { pattern: 'хлопь', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'мюсл', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'гранол', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'завтрак', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'отруб', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'подсолнечное масло', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'оливковое масло', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'растительное масло', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'масло подсолнеч', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'масло оливков', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'соль', cat: 'grocery', sub: 'salt' },
  { pattern: 'уксус', cat: 'grocery', sub: 'vinegar' },
  { pattern: 'соус', cat: 'sauces_spices', sub: 'sauce' },
  { pattern: 'майонез', cat: 'sauces_spices', sub: 'mayo_ketchup' },
  { pattern: 'кетчуп', cat: 'sauces_spices', sub: 'mayo_ketchup' },
  { pattern: 'специй', cat: 'sauces_spices', sub: 'spices' },
  { pattern: 'приправ', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'перец', cat: 'sauces_spices', sub: 'spices' },
  { pattern: 'кунжут', cat: 'sauces_spices', sub: 'spices' },
  { pattern: 'горчиц', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'хрен', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'бульон', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'томатная паста', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'соевый соус', cat: 'sauces_spices', sub: 'soy_sauce' },
  { pattern: 'хлеб', cat: 'bread', sub: 'bread' },
  { pattern: 'батон', cat: 'bread', sub: 'bread' },
  { pattern: 'лаваш', cat: 'bread', sub: 'lavash' },
  { pattern: 'лепёшк', cat: 'bread', sub: 'lavash' },
  { pattern: 'лепешк', cat: 'bread', sub: 'lavash' },
  { pattern: 'чиабатт', cat: 'bread', sub: 'pastry' },
  { pattern: 'булочк', cat: 'bread', sub: 'pastry' },
  { pattern: 'багет', cat: 'bread', sub: 'pastry' },
  { pattern: 'хлебц', cat: 'bread', sub: 'crispbread' },
  { pattern: 'слайс', cat: 'bread', sub: 'crispbread' },
  { pattern: 'морожен', cat: 'frozen', sub: 'ice_cream' },
  { pattern: 'эскимо', cat: 'frozen', sub: 'ice_cream' },
  { pattern: 'пломбир', cat: 'frozen', sub: 'ice_cream' },
  { pattern: 'пельмен', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'вареник', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'котлет', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'тефтел', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'фрикадельк', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'наггетс', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'полуфабрикат', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'блинчик', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'пицц', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'тесто', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'замороженн', cat: 'frozen', sub: 'frozen_veg' },
  { pattern: 'овощ', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'картофел', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'огурц', cat: 'fruits_veg', sub: 'pickles' },
  { pattern: 'помидор', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'томат', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'оливк', cat: 'fruits_veg', sub: 'olives' },
  { pattern: 'маслин', cat: 'fruits_veg', sub: 'olives' },
  { pattern: 'зелень', cat: 'fruits_veg', sub: 'greens' },
  { pattern: 'фрукт', cat: 'fruits_veg', sub: 'fruits' },
  { pattern: 'яблок', cat: 'fruits_veg', sub: 'fruits' },
  { pattern: 'банан', cat: 'fruits_veg', sub: 'fruits' },
  { pattern: 'гриб', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'солень', cat: 'fruits_veg', sub: 'pickles' },
  { pattern: 'маринован', cat: 'fruits_veg', sub: 'pickles' },
  { pattern: 'фрутоняня', cat: 'baby_food', sub: 'puree' },
  { pattern: 'агуша', cat: 'baby_food', sub: 'puree' },
  { pattern: 'детское питан', cat: 'baby_food', sub: 'puree' },
  { pattern: 'пюре', cat: 'baby_food', sub: 'puree' },
  { pattern: 'детская каш', cat: 'baby_food', sub: 'cereal' },
  { pattern: 'смесь молочн', cat: 'baby_food', sub: 'formula' },
  { pattern: 'kabrita', cat: 'baby_food', sub: 'formula' },
  { pattern: 'nestle шагайка', cat: 'baby_food', sub: 'cereal' },
  { pattern: 'суп ', cat: 'ready_meals', sub: 'soups' },
  { pattern: 'быстрого приготовлен', cat: 'ready_meals', sub: 'instant' },
  { pattern: 'лапша быстр', cat: 'ready_meals', sub: 'instant' },
  { pattern: 'доширак', cat: 'ready_meals', sub: 'instant' },
  { pattern: 'роллтон', cat: 'ready_meals', sub: 'instant' },
  { pattern: 'протеин', cat: 'healthy', sub: 'protein' },
  { pattern: 'белковый батончик', cat: 'healthy', sub: 'protein' },
  { pattern: 'без сахара', cat: 'healthy', sub: 'sugar_free' },
  { pattern: 'б.сах', cat: 'healthy', sub: 'sugar_free' },
  { pattern: 'безглютен', cat: 'healthy', sub: 'gluten_free' },
  { pattern: 'без глютен', cat: 'healthy', sub: 'gluten_free' },
  { pattern: 'глютен-free', cat: 'healthy', sub: 'gluten_free' },
  { pattern: 'пп-', cat: 'healthy', sub: 'diet' },
  { pattern: 'сахарозамен', cat: 'healthy', sub: 'sugar_free' },
  { pattern: 'стеви', cat: 'healthy', sub: 'sugar_free' },
  { pattern: 'эритрит', cat: 'healthy', sub: 'sugar_free' },
  { pattern: 'дәрумен', cat: 'healthy', sub: 'vitamins' },
  { pattern: 'витамин', cat: 'healthy', sub: 'vitamins' },
  { pattern: 'бад', cat: 'healthy', sub: 'supplements' },
  { pattern: 'омега', cat: 'healthy', sub: 'supplements' },
  { pattern: 'шампун', cat: 'personal_care', sub: 'shampoo' },
  { pattern: 'мыло', cat: 'personal_care', sub: 'soap' },
  { pattern: 'крем ', cat: 'personal_care', sub: 'cream' },
  { pattern: 'зубн', cat: 'personal_care', sub: 'dental' },
  { pattern: 'гель для душа', cat: 'personal_care', sub: 'hygiene' },
  { pattern: 'дезодорант', cat: 'personal_care', sub: 'hygiene' },
  { pattern: 'корм', cat: 'household', sub: 'pet_food' },
  { pattern: 'лакомство для', cat: 'household', sub: 'pet_food' },
  { pattern: 'моющ', cat: 'household', sub: 'cleaning' },
  { pattern: 'салфетк', cat: 'household', sub: 'paper' },
  { pattern: 'бумажн', cat: 'household', sub: 'paper' },
  { pattern: 'стиральн', cat: 'household', sub: 'laundry' },
  { pattern: 'порошок', cat: 'household', sub: 'laundry' },
  { pattern: 'пиво', cat: DEACTIVATE, sub: null },
  { pattern: 'вино', cat: DEACTIVATE, sub: null },
  { pattern: 'водк', cat: DEACTIVATE, sub: null },
  { pattern: 'коньяк', cat: DEACTIVATE, sub: null },
  { pattern: 'виски', cat: DEACTIVATE, sub: null },
  { pattern: 'ром ', cat: DEACTIVATE, sub: null },
  { pattern: 'джин ', cat: DEACTIVATE, sub: null },
  { pattern: 'текил', cat: DEACTIVATE, sub: null },
  { pattern: 'абсент', cat: DEACTIVATE, sub: null },
  { pattern: 'сидр', cat: DEACTIVATE, sub: null },
  { pattern: 'эль ', cat: DEACTIVATE, sub: null },
  { pattern: 'клей', cat: DEACTIVATE, sub: null },
  { pattern: 'туфли', cat: DEACTIVATE, sub: null },
  { pattern: 'шампун', cat: 'personal_care', sub: 'shampoo' },
  { pattern: 'палочки крабов', cat: 'fish', sub: 'seafood' },
  { pattern: 'крабовые палочки', cat: 'fish', sub: 'seafood' },
  { pattern: 'масло ', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'cheese', cat: 'dairy_eggs', sub: 'cheese' },
  { pattern: 'milk', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'yogurt', cat: 'dairy_eggs', sub: 'fermented' },
  { pattern: 'butter', cat: 'dairy_eggs', sub: 'butter' },
  { pattern: 'cream', cat: 'dairy_eggs', sub: 'cream' },
  { pattern: 'juice', cat: 'water_beverages', sub: 'juice' },
  { pattern: 'water', cat: 'water_beverages', sub: 'water' },
  { pattern: 'soda', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'nuts', cat: 'snacks', sub: 'nuts' },
  { pattern: 'chips', cat: 'snacks', sub: 'chips' },
  { pattern: 'snack', cat: 'snacks', sub: 'chips' },
  { pattern: 'candy', cat: 'sweets', sub: 'candy' },
  { pattern: 'cookie', cat: 'sweets', sub: 'cookies' },
  { pattern: 'biscuit', cat: 'sweets', sub: 'cookies' },
  { pattern: 'pasta', cat: 'grocery', sub: 'pasta' },
  { pattern: 'rice', cat: 'grocery', sub: 'rice' },
  { pattern: 'flour', cat: 'grocery', sub: 'flour' },
  { pattern: 'sugar', cat: 'grocery', sub: 'sugar' },
  { pattern: 'oil', cat: 'grocery', sub: 'cooking_oil' },
  { pattern: 'sauce', cat: 'sauces_spices', sub: 'sauce' },
  { pattern: 'spice', cat: 'sauces_spices', sub: 'spices' },
  { pattern: 'season', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'condiment', cat: 'sauces_spices', sub: 'condiments' },
  { pattern: 'bread', cat: 'bread', sub: 'bread' },
  { pattern: 'bakery', cat: 'bread', sub: 'pastry' },
  { pattern: 'frozen', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'meat', cat: 'meat', sub: 'raw' },
  { pattern: 'fish', cat: 'fish', sub: 'fish' },
  { pattern: 'seafood', cat: 'fish', sub: 'seafood' },
  { pattern: 'canned', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'cereal', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'muesli', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'granola', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'breakfast', cat: 'grocery', sub: 'breakfast' },
  { pattern: 'honey', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'jam', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'halal', cat: 'deli', sub: 'sausage' },
  { pattern: 'tea', cat: 'tea_coffee', sub: 'tea' },
  { pattern: 'шампиньон', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'гриб', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'кукуруз', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'горошек', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'фасол', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'чечевиц', cat: 'grocery', sub: 'cereals' },
  { pattern: 'нут ', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'бондинг', cat: 'fruits_veg', sub: 'canned_veg' },
  { pattern: 'schweppes', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'тоник', cat: 'water_beverages', sub: 'soda' },
  { pattern: 'lipton', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'резинка жевательн', cat: 'sweets', sub: 'candy' },
  { pattern: 'жевательн', cat: 'sweets', sub: 'candy' },
  { pattern: 'леденец', cat: 'sweets', sub: 'candy' },
  { pattern: 'орбит', cat: 'sweets', sub: 'candy' },
  { pattern: 'wrigley', cat: 'sweets', sub: 'candy' },
  { pattern: 'eclipse', cat: 'sweets', sub: 'candy' },
  { pattern: 'dirol', cat: 'sweets', sub: 'candy' },
  { pattern: 'm&m', cat: 'sweets', sub: 'candy' },
  { pattern: 'драже', cat: 'sweets', sub: 'candy' },
  { pattern: 'marshmallow', cat: 'sweets', sub: 'candy' },
  { pattern: 'маршмеллоу', cat: 'sweets', sub: 'candy' },
  { pattern: 'кокосовая стружка', cat: 'grocery', sub: 'flour' },
  { pattern: 'лимонная кислота', cat: 'grocery', sub: 'salt' },
  { pattern: 'сода пищев', cat: 'grocery', sub: 'salt' },
  { pattern: 'крахмал', cat: 'grocery', sub: 'flour' },
  { pattern: 'желатин', cat: 'grocery', sub: 'flour' },
  { pattern: 'разрыхлитель', cat: 'grocery', sub: 'flour' },
  { pattern: 'ванил', cat: 'grocery', sub: 'flour' },
  { pattern: 'премикс', cat: 'grocery', sub: 'flour' },
  { pattern: 'сироп', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'топпинг', cat: 'sweets', sub: 'honey_jam' },
  { pattern: 'пудинг', cat: 'sweets', sub: 'candy' },
  { pattern: 'десерт', cat: 'sweets', sub: 'candy' },
  { pattern: 'молочный напиток', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'напиток', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'курдюк', cat: 'deli', sub: 'smoked' },
  { pattern: 'говядин', cat: 'meat', sub: 'raw' },
  { pattern: 'свинин', cat: 'meat', sub: 'raw' },
  { pattern: 'баранин', cat: 'meat', sub: 'raw' },
  { pattern: 'фарш', cat: 'meat', sub: 'raw' },
  { pattern: 'индейк', cat: 'meat', sub: 'poultry' },
  { pattern: 'куриц', cat: 'meat', sub: 'poultry' },
  { pattern: 'крыло', cat: 'meat', sub: 'poultry' },
  { pattern: 'сервелат', cat: 'deli', sub: 'sausage' },
  { pattern: 'рулет мясн', cat: 'deli', sub: 'deli_meat' },
  { pattern: 'сельдь', cat: 'fish', sub: 'canned_fish' },
  { pattern: 'скумбри', cat: 'fish', sub: 'canned_fish' },
  { pattern: 'горбуш', cat: 'fish', sub: 'canned_fish' },
  { pattern: 'форел', cat: 'fish', sub: 'fish' },
  { pattern: 'сурими', cat: 'fish', sub: 'seafood' },
  { pattern: 'лапша', cat: 'grocery', sub: 'pasta' },
  { pattern: 'соба', cat: 'grocery', sub: 'pasta' },
  { pattern: 'книга', cat: DEACTIVATE, sub: null },
  { pattern: 'сигар', cat: DEACTIVATE, sub: null },
  { pattern: 'подгузник', cat: 'household', sub: 'hygiene' },
  { pattern: 'трусики', cat: 'household', sub: 'hygiene' },
  { pattern: 'гель для посуд', cat: 'household', sub: 'cleaning' },
  { pattern: 'fairy', cat: 'household', sub: 'cleaning' },
  { pattern: 'domestos', cat: 'household', sub: 'cleaning' },
  { pattern: 'mr.proper', cat: 'household', sub: 'cleaning' },
  { pattern: 'средство', cat: 'household', sub: 'cleaning' },
  { pattern: 'спрей', cat: 'household', sub: 'cleaning' },
  { pattern: 'биомио', cat: 'household', sub: 'cleaning' },
  { pattern: 'тоник для лиц', cat: 'personal_care', sub: 'cream' },
  { pattern: 'garnier', cat: 'personal_care', sub: 'cream' },
  { pattern: 'nivea', cat: 'personal_care', sub: 'hygiene' },
  { pattern: 'гель-уход', cat: 'personal_care', sub: 'hygiene' },
  { pattern: 'гель для душа', cat: 'personal_care', sub: 'hygiene' },
  { pattern: 'скраб для лиц', cat: 'personal_care', sub: 'cream' },
  { pattern: 'скраб', cat: 'personal_care', sub: 'cream' },
  { pattern: 'смесь nestle', cat: 'baby_food', sub: 'formula' },
  { pattern: 'nestogen', cat: 'baby_food', sub: 'formula' },
  { pattern: 'каша гречневая с говядин', cat: 'deli', sub: 'canned_meat' },
  { pattern: 'ruellet', cat: 'bread', sub: 'pastry' },
  { pattern: 'рулет', cat: 'bread', sub: 'pastry' },
  { pattern: 'oknomoyka', cat: 'household', sub: 'cleaning' },
  { pattern: 'master fresh', cat: 'household', sub: 'cleaning' },
  { pattern: 'груда', cat: 'fruits_veg', sub: 'fruits' },
  { pattern: 'груш', cat: 'fruits_veg', sub: 'fruits' },
  { pattern: 'окра', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'спарж', cat: 'fruits_veg', sub: 'vegetables' },
  { pattern: 'пастіла', cat: 'sweets', sub: 'candy' },
  { pattern: 'пастила', cat: 'sweets', sub: 'candy' },
  { pattern: 'плитка', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'орех', cat: 'snacks', sub: 'nuts' },
  { pattern: 'alpro', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'nemoloko', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'оших', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'соев', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'кокосов', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'овсян', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'миндальн', cat: 'dairy_eggs', sub: 'milk' },
  { pattern: 'тарталетк', cat: 'snacks', sub: 'crackers' },
  { pattern: 'виспа', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'wispa', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'бісквіт', cat: 'sweets', sub: 'cookies' },
  { pattern: 'бисквит', cat: 'sweets', sub: 'cookies' },
  { pattern: 'сухар', cat: 'snacks', sub: 'crackers' },
  { pattern: 'жаренк', cat: 'frozen', sub: 'semi_finished' },
  { pattern: ' набор', cat: 'sweets', sub: 'candy' },
  { pattern: 'сет праздничн', cat: 'sweets', sub: 'candy' },
  { pattern: 'бонжур', cat: 'snacks', sub: 'crackers' },
  { pattern: 'солнечная кухня', cat: 'sweets', sub: 'candy' },
  { pattern: 'счасть', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'сибирский кедр', cat: 'sweets', sub: 'candy' },
  { pattern: 'зеленая', cat: 'household', sub: 'cleaning' },
  { pattern: 'christmas', cat: DEACTIVATE, sub: null },
  { pattern: 'цепи грм', cat: DEACTIVATE, sub: null },
  { pattern: 'masuma', cat: DEACTIVATE, sub: null },
  { pattern: 'jacobs', cat: 'tea_coffee', sub: 'coffee' },
  { pattern: "jacob's creek", cat: DEACTIVATE, sub: null },
  { pattern: 'rose розовое', cat: DEACTIVATE, sub: null },
  { pattern: 'tagliolini', cat: 'grocery', sub: 'pasta' },
  { pattern: 'doritos', cat: 'snacks', sub: 'chips' },
  { pattern: 'nutella', cat: 'sweets', sub: 'chocolate' },
  { pattern: 'мазь', cat: DEACTIVATE, sub: null },
  { pattern: 'sweet sweat', cat: DEACTIVATE, sub: null },
  { pattern: 'macchiato', cat: 'tea_coffee', sub: 'coffee' },
  { pattern: 'ice macchiato', cat: 'water_beverages', sub: 'lemonade' },
  { pattern: 'сырник', cat: 'frozen', sub: 'semi_finished' },
  { pattern: 'bien', cat: 'snacks', sub: 'crackers' },
]

const VALID_CATEGORIES = new Set(Object.keys(CATEGORIES))

const GENERIC_CATEGORIES = new Set([
  'grocery',
  'snacks',
  'beverages',
  'dairy',
  'condiments',
  'plant-based-foods-and-beverages',
  'beverages-and-beverages-preparations',
])

export function classifyByName(name, brand) {
  if (!name && !brand) return null
  const text = `${name || ''} ${brand || ''}`.toLowerCase()
  for (const rule of NAME_KEYWORDS) {
    if (text.includes(rule.pattern.toLowerCase())) {
      return { category: rule.cat, subcategory: rule.sub }
    }
  }
  return null
}

export function getCategoryLabel(key, lang) {
  if (!key || !CATEGORIES[key]) return key || ''
  const cat = CATEGORIES[key]
  return lang === 'kz' ? cat.kz : cat.ru
}

export function getSubcategoryLabel(catKey, subKey, lang) {
  if (!catKey || !subKey) return ''
  const cat = CATEGORIES[catKey]
  if (!cat || !cat.subcategories[subKey]) return subKey || ''
  const sub = cat.subcategories[subKey]
  return lang === 'kz' ? sub.kz : sub.ru
}

export function getAllCategoryKeys() {
  return Object.keys(CATEGORIES)
}

export function getSubcategoryKeys(catKey) {
  const cat = CATEGORIES[catKey]
  if (!cat || !cat.subcategories) return []
  return Object.keys(cat.subcategories)
}

export function normalizeCategory(rawCategory, rawSubcategory, name, brand) {
  if (rawCategory && VALID_CATEGORIES.has(rawCategory)) {
    return { category: rawCategory, subcategory: rawSubcategory || null }
  }

  if (rawCategory && RAW_CATEGORY_MAP[rawCategory]) {
    const mapped = RAW_CATEGORY_MAP[rawCategory]
    if (mapped.subcategory) return mapped
    if (rawSubcategory && RAW_SUBCATEGORY_MAP[rawSubcategory]) {
      return {
        category: mapped.category,
        subcategory: RAW_SUBCATEGORY_MAP[rawSubcategory].subcategory,
      }
    }
    return mapped
  }

  if (rawCategory && GENERIC_CATEGORIES.has(rawCategory)) {
    const byName = classifyByName(name, brand)
    if (byName) return byName
  }

  if (!rawCategory || rawCategory === '') {
    const byName = classifyByName(name, brand)
    if (byName) return byName
  }

  const byName = classifyByName(name, brand)
  if (byName) return byName

  return { category: 'grocery', subcategory: null }
}

export {
  RAW_CATEGORY_MAP,
  RAW_SUBCATEGORY_MAP,
  NAME_KEYWORDS,
  GENERIC_CATEGORIES,
  VALID_CATEGORIES,
}
